# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'tare_screen.ui'
##
## Created by: Qt User Interface Compiler version 6.7.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QPushButton,
    QSizePolicy, QWidget)

class Ui_Tare(object):
    def setupUi(self, Tare):
        if not Tare.objectName():
            Tare.setObjectName(u"Tare")
        Tare.resize(1024, 600)
        Tare.setStyleSheet(u"")
        self.centralwidget = QWidget(Tare)
        self.centralwidget.setObjectName(u"centralwidget")
        self.oneA = QPushButton(self.centralwidget)
        self.oneA.setObjectName(u"oneA")
        self.oneA.setGeometry(QRect(20, 10, 111, 261))
        self.oneB = QPushButton(self.centralwidget)
        self.oneB.setObjectName(u"oneB")
        self.oneB.setGeometry(QRect(140, 10, 111, 261))
        self.oneC = QPushButton(self.centralwidget)
        self.oneC.setObjectName(u"oneC")
        self.oneC.setGeometry(QRect(260, 10, 111, 261))
        self.oneD = QPushButton(self.centralwidget)
        self.oneD.setObjectName(u"oneD")
        self.oneD.setGeometry(QRect(380, 10, 111, 261))
        self.twoA = QPushButton(self.centralwidget)
        self.twoA.setObjectName(u"twoA")
        self.twoA.setGeometry(QRect(530, 10, 111, 261))
        self.twoB = QPushButton(self.centralwidget)
        self.twoB.setObjectName(u"twoB")
        self.twoB.setGeometry(QRect(650, 10, 111, 261))
        self.twoC = QPushButton(self.centralwidget)
        self.twoC.setObjectName(u"twoC")
        self.twoC.setGeometry(QRect(770, 10, 111, 261))
        self.twoD = QPushButton(self.centralwidget)
        self.twoD.setObjectName(u"twoD")
        self.twoD.setGeometry(QRect(890, 10, 111, 261))
        self.threeA = QPushButton(self.centralwidget)
        self.threeA.setObjectName(u"threeA")
        self.threeA.setGeometry(QRect(20, 320, 111, 261))
        self.threeB = QPushButton(self.centralwidget)
        self.threeB.setObjectName(u"threeB")
        self.threeB.setGeometry(QRect(140, 320, 111, 261))
        self.threeC = QPushButton(self.centralwidget)
        self.threeC.setObjectName(u"threeC")
        self.threeC.setGeometry(QRect(260, 320, 111, 261))
        self.threeD = QPushButton(self.centralwidget)
        self.threeD.setObjectName(u"threeD")
        self.threeD.setGeometry(QRect(380, 320, 111, 261))
        self.fourA = QPushButton(self.centralwidget)
        self.fourA.setObjectName(u"fourA")
        self.fourA.setGeometry(QRect(530, 320, 111, 261))
        self.fourB = QPushButton(self.centralwidget)
        self.fourB.setObjectName(u"fourB")
        self.fourB.setGeometry(QRect(650, 320, 111, 261))
        self.fourC = QPushButton(self.centralwidget)
        self.fourC.setObjectName(u"fourC")
        self.fourC.setGeometry(QRect(770, 320, 111, 261))
        self.fourD = QPushButton(self.centralwidget)
        self.fourD.setObjectName(u"fourD")
        self.fourD.setGeometry(QRect(890, 320, 111, 261))
        self.oneAValue = QLabel(self.centralwidget)
        self.oneAValue.setObjectName(u"oneAValue")
        self.oneAValue.setGeometry(QRect(30, 200, 91, 61))
        self.oneBValue = QLabel(self.centralwidget)
        self.oneBValue.setObjectName(u"oneBValue")
        self.oneBValue.setGeometry(QRect(150, 200, 91, 61))
        self.oneCValue = QLabel(self.centralwidget)
        self.oneCValue.setObjectName(u"oneCValue")
        self.oneCValue.setGeometry(QRect(270, 200, 91, 61))
        self.oneDValue = QLabel(self.centralwidget)
        self.oneDValue.setObjectName(u"oneDValue")
        self.oneDValue.setGeometry(QRect(390, 200, 91, 61))
        self.twoAValue = QLabel(self.centralwidget)
        self.twoAValue.setObjectName(u"twoAValue")
        self.twoAValue.setGeometry(QRect(540, 200, 91, 61))
        self.twoBValue = QLabel(self.centralwidget)
        self.twoBValue.setObjectName(u"twoBValue")
        self.twoBValue.setGeometry(QRect(660, 200, 91, 61))
        self.twoCValue = QLabel(self.centralwidget)
        self.twoCValue.setObjectName(u"twoCValue")
        self.twoCValue.setGeometry(QRect(780, 200, 91, 61))
        self.twoDValue = QLabel(self.centralwidget)
        self.twoDValue.setObjectName(u"twoDValue")
        self.twoDValue.setGeometry(QRect(900, 200, 91, 61))
        self.threeAValue = QLabel(self.centralwidget)
        self.threeAValue.setObjectName(u"threeAValue")
        self.threeAValue.setGeometry(QRect(30, 510, 91, 61))
        self.threeBValue = QLabel(self.centralwidget)
        self.threeBValue.setObjectName(u"threeBValue")
        self.threeBValue.setGeometry(QRect(150, 510, 91, 61))
        self.threeCValue = QLabel(self.centralwidget)
        self.threeCValue.setObjectName(u"threeCValue")
        self.threeCValue.setGeometry(QRect(270, 510, 91, 61))
        self.threeDValue = QLabel(self.centralwidget)
        self.threeDValue.setObjectName(u"threeDValue")
        self.threeDValue.setGeometry(QRect(390, 510, 91, 61))
        self.fourAValue = QLabel(self.centralwidget)
        self.fourAValue.setObjectName(u"fourAValue")
        self.fourAValue.setGeometry(QRect(540, 510, 91, 61))
        self.fourBValue = QLabel(self.centralwidget)
        self.fourBValue.setObjectName(u"fourBValue")
        self.fourBValue.setGeometry(QRect(660, 510, 91, 61))
        self.fourCValue = QLabel(self.centralwidget)
        self.fourCValue.setObjectName(u"fourCValue")
        self.fourCValue.setGeometry(QRect(780, 510, 91, 61))
        self.fourDValue = QLabel(self.centralwidget)
        self.fourDValue.setObjectName(u"fourDValue")
        self.fourDValue.setGeometry(QRect(900, 510, 91, 61))
        self.exitButton = QPushButton(self.centralwidget)
        self.exitButton.setObjectName(u"exitButton")
        self.exitButton.setGeometry(QRect(460, 271, 101, 41))
        Tare.setCentralWidget(self.centralwidget)

        self.retranslateUi(Tare)

        QMetaObject.connectSlotsByName(Tare)
    # setupUi

    def retranslateUi(self, Tare):
        Tare.setWindowTitle(QCoreApplication.translate("Tare", u"MainWindow", None))
        self.oneA.setText(QCoreApplication.translate("Tare", u"1A", None))
        self.oneA.setProperty(u"type", QCoreApplication.translate("Tare", u"normal", None))
        self.oneB.setText(QCoreApplication.translate("Tare", u"1B", None))
        self.oneB.setProperty(u"type", QCoreApplication.translate("Tare", u"normal", None))
        self.oneC.setText(QCoreApplication.translate("Tare", u"1C", None))
        self.oneC.setProperty(u"type", QCoreApplication.translate("Tare", u"normal", None))
        self.oneD.setText(QCoreApplication.translate("Tare", u"1D", None))
        self.oneD.setProperty(u"type", QCoreApplication.translate("Tare", u"normal", None))
        self.twoA.setText(QCoreApplication.translate("Tare", u"2A", None))
        self.twoA.setProperty(u"type", QCoreApplication.translate("Tare", u"normal", None))
        self.twoB.setText(QCoreApplication.translate("Tare", u"2B", None))
        self.twoB.setProperty(u"type", QCoreApplication.translate("Tare", u"normal", None))
        self.twoC.setText(QCoreApplication.translate("Tare", u"2C", None))
        self.twoC.setProperty(u"type", QCoreApplication.translate("Tare", u"normal", None))
        self.twoD.setText(QCoreApplication.translate("Tare", u"2D", None))
        self.twoD.setProperty(u"type", QCoreApplication.translate("Tare", u"normal", None))
        self.threeA.setText(QCoreApplication.translate("Tare", u"3A", None))
        self.threeA.setProperty(u"type", QCoreApplication.translate("Tare", u"normal", None))
        self.threeB.setText(QCoreApplication.translate("Tare", u"3B", None))
        self.threeB.setProperty(u"type", QCoreApplication.translate("Tare", u"normal", None))
        self.threeC.setText(QCoreApplication.translate("Tare", u"3C", None))
        self.threeC.setProperty(u"type", QCoreApplication.translate("Tare", u"normal", None))
        self.threeD.setText(QCoreApplication.translate("Tare", u"3D", None))
        self.threeD.setProperty(u"type", QCoreApplication.translate("Tare", u"normal", None))
        self.fourA.setText(QCoreApplication.translate("Tare", u"4A", None))
        self.fourA.setProperty(u"type", QCoreApplication.translate("Tare", u"normal", None))
        self.fourB.setText(QCoreApplication.translate("Tare", u"4B", None))
        self.fourB.setProperty(u"type", QCoreApplication.translate("Tare", u"normal", None))
        self.fourC.setText(QCoreApplication.translate("Tare", u"4C", None))
        self.fourC.setProperty(u"type", QCoreApplication.translate("Tare", u"normal", None))
        self.fourD.setText(QCoreApplication.translate("Tare", u"4D", None))
        self.fourD.setProperty(u"type", QCoreApplication.translate("Tare", u"normal", None))
        self.oneAValue.setText(QCoreApplication.translate("Tare", u"TextLabel", None))
        self.oneBValue.setText(QCoreApplication.translate("Tare", u"TextLabel", None))
        self.oneCValue.setText(QCoreApplication.translate("Tare", u"TextLabel", None))
        self.oneDValue.setText(QCoreApplication.translate("Tare", u"TextLabel", None))
        self.twoAValue.setText(QCoreApplication.translate("Tare", u"TextLabel", None))
        self.twoBValue.setText(QCoreApplication.translate("Tare", u"TextLabel", None))
        self.twoCValue.setText(QCoreApplication.translate("Tare", u"TextLabel", None))
        self.twoDValue.setText(QCoreApplication.translate("Tare", u"TextLabel", None))
        self.threeAValue.setText(QCoreApplication.translate("Tare", u"TextLabel", None))
        self.threeBValue.setText(QCoreApplication.translate("Tare", u"TextLabel", None))
        self.threeCValue.setText(QCoreApplication.translate("Tare", u"TextLabel", None))
        self.threeDValue.setText(QCoreApplication.translate("Tare", u"TextLabel", None))
        self.fourAValue.setText(QCoreApplication.translate("Tare", u"TextLabel", None))
        self.fourBValue.setText(QCoreApplication.translate("Tare", u"TextLabel", None))
        self.fourCValue.setText(QCoreApplication.translate("Tare", u"TextLabel", None))
        self.fourDValue.setText(QCoreApplication.translate("Tare", u"TextLabel", None))
        self.exitButton.setText(QCoreApplication.translate("Tare", u"Exit", None))
    # retranslateUi

